version: '3.9'

services:

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:15.3-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ../.env

  backend:
    image: k1n8/prosept_app:latest
    restart: always
    env_file:
      - ../.env
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  db_data:
