version: '3.3'

services:

  frontend:
    image: hackaton1pros/prosept:latest
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ../.env

  backend:
    image: k1n8/prosept_app:latest
    restart: always
    command: "sh -c 'alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --timeout 1800'"
    env_file:
      - ../.env
    depends_on:
      - db
    mem_limit: 4g
    deploy:
      resources:
        limits:
          memory: 3500M

  nginx:
    image: nginx:1.21.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/dist:/usr/share/nginx/html/
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 350M

volumes:
  db_data:
