"""commit1

Revision ID: bddc6c82011c
Revises: 73c77d0f09e3
Create Date: 2023-11-25 10:12:47.858163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bddc6c82011c'
down_revision = '73c77d0f09e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('артикул товара', sa.String(length=100), nullable=False),
    sa.Column('код товара', sa.Integer(), nullable=True),
    sa.Column('название товара', sa.String(length=1000), nullable=True),
    sa.Column('стоимость', sa.Float(), nullable=True),
    sa.Column('рекомендованная минимальная цена', sa.Float(), nullable=True),
    sa.Column('рекомендованная цена', sa.Float(), nullable=True),
    sa.Column('категория товара', sa.Integer(), nullable=True),
    sa.Column('названиет товара на Озоне', sa.String(length=1000), nullable=True),
    sa.Column('название товара в 1C', sa.String(length=1000), nullable=True),
    sa.Column('название товара на Wildberries', sa.String(length=1000), nullable=True),
    sa.Column('описание для Озон', sa.Integer(), nullable=True),
    sa.Column('артикул для Wildberries', sa.Integer(), nullable=True),
    sa.Column('артикул для Wildberries td', sa.String(length=100), nullable=True),
    sa.Column('артикул для Яндекс.Маркета', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('артикул товара')
    )
    op.create_table('dealerprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('уникальный номер позиции', sa.Integer(), nullable=False),
    sa.Column('цена', sa.Float(), nullable=False),
    sa.Column('адрес страницы, откуда собраны данные', sa.String(length=1000), nullable=True),
    sa.Column('заголовок продаваемого товара', sa.String(length=1000), nullable=False),
    sa.Column('дата получения информации', sa.Date(), nullable=False),
    sa.Column('идентификатор дилера', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['идентификатор дилера'], ['dealer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productdealerkey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('идентификатор товара', sa.Integer(), nullable=True),
    sa.Column('идентификатор дилера', sa.Integer(), nullable=True),
    sa.Column('идентификатор продукта', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['идентификатор дилера'], ['dealer.id'], ),
    sa.ForeignKeyConstraint(['идентификатор продукта'], ['product.id'], ),
    sa.ForeignKeyConstraint(['идентификатор товара'], ['productdealerkey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('data')
    op.drop_table('meters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meters',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('meters_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='meters_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='meters_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('A', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kW', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], name='data_meter_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='data_pkey')
    )
    op.drop_table('productdealerkey')
    op.drop_table('dealerprice')
    op.drop_table('product')
    op.drop_table('dealer')
    # ### end Alembic commands ###
